### ISSUE TITLE
Usage with Api V2?

### ISSUE THREAD

**Issue by kLOsk** [ArkEcosystem/php-client#25]
I'm trying to use this along with api v2, but unfortunate can't get any meaningful information from the objects. For example this here:
<code><pre><?php
use ArkEcosystem\Client\Connection;

 $connection = new Connection([
     'host' => 'http://0.0.0.0:4003', // NO TRAILING SLASH!
     'version' => 2
 ]);

$wallets = $connection->wallets();

echo '<pre>';
print_r($wallets);
echo '</pre>';
?>
</pre></code>

The only thing I get from the walets object are guzzle objects. When trying to access the all() method I get an error. Can you provide some help here? Thanks!

**Comment by reConNico** [comment]
Hey @kLOsk ,

can you try the following configuration:

```
$connection = new Connection([
    'host' => 'https://explorer.ark.io:8443/api/',
    'version' => 2, // you can remove this one because it isn't used by the client
]);
```

That should definitely work. There is also a minimalistic demo documentation: https://docs.ark.io/sdk/examples/sdk-demos.html#php

**Comment by repat** [comment]
@kLOsk Might your error might've been related to #93, should be fixed in the next release. You _do_ need a trailing slash, otherwise you get a PHP return type error. A slash will automatically be added in the new release as well.

@reConNico not everyday you meet a neighbor on the interwebs, hallo aus quickborn ;)
